// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtqavoujjwgkiyhcjuip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cWF2b3Vqandna2l5aGNqdWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzU4MzEsImV4cCI6MjA2MTExMTgzMX0.M05U5OLubbbISoribW32FKW783jyopYASphOkwlDPvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);